#' @include hicpro.R
NULL

#' Export sparseHiCdatum to DNAlandscapeR files
#'
#' \code{exportDNAlandscapeR} takes a \code{sparseHiCdatum} object
#' and produces two files, a .rds and a .resolutions.txt file
#' that can be used in DNAlandscapeR (dnalandscaper.aryeelab.org).
#'
#' @param dat A \code{sparseHiCdatum} object
#' @param newSampleName = "" New sample name for the object, if desired. Current
#' one in the object is used by default.
#' @param out.dir = "" The output directory to save the new files
#'
#' @return Will produce two files in the specified out.dir
#'
#' @examples
#' # Computing normalizing factors from the full ChIA-PET Data
#' genomeBuild <- "hg19"

#' @export
setGeneric(name = "exportDNAlandscapeR", def = function(dat, newSampleName = "", out.dir = "") standardGeneric("exportDNAlandscapeR"))

#' @rdname exportDNAlandscapeR
setMethod("exportDNAlandscapeR", c("sparseHiCdatum"), function(dat, newSampleName = "", out.dir = "") {
    
    if(newSampleName == "") newSampleName <- dat@sampleName  
    ss <- paste0(newSampleName, "-HiC")
    res <- names(dat@resolutionNamedList)
    warn <- "Do not edit this file; keep it in the same directory as the .rds for visualizing in DNAlandscapeR"
    outText <- c(warn, ss, paste(res, collapse = ","))
    
    # Output .txt file
    fileConn<-file(paste0(out.dir, ss, ".resolutions.txt"))
    writeLines(outText, fileConn)
    close(fileConn)

    rdsFile<-file(paste0(out.dir, ss, ".rds"))
    saveRDS(dat, file = rdsFile)
})


#' Export DNAlandscapeR files straight from HiC Pro Output
#'
#' \code{HiCPro2DNAlandscapeR} takes the input files from
#' HiC Pro output and creates a .rds and a .resolutions.txt
#' set of files that can be visualized in
#' DNAlandscapeR (dnalandscaper.aryeelab.org).
#'
#' @param matrix.files Path to .matrix files from Hi-C Pro Output
#' @param bed.files Path to .bed files from Hi-C Pro Output
#' @param resolutions Character vector of the resolutions of the Hi-C output
#' @param sampleName Single string of Hi-C data sample that is imported. "-HiC" will 
#' automatically be appended.
#' @param genomeBuild = NA Can specify one of c("hg38", "hg19", "hg18", "mm10", "mm9", "mm8")
#' that are built-in options for Hi-C chromosomes and distances. If not of these options
#' are suitable, then use the \code{manual.chr} and \code{manual.dist} parameters
#' @param out.dir = "" The output directory to save the new files
#' @param drop.chrom = c("chrY", "chrM") Chromosomes dropped from compression
#' @param manual.chr = NA Specify a vector of chromosome names in the data
#' @param manual.dist = NA Specify a same length vector as manual.chr with the 
#' chromosomal distances corresponding to each element in the manual.chr
#' @param BPPARAM = bpparam() Parameters to pass to bplapply
#'
#' @return Will produce two files in the specified out.dir
#'
#' @examples
#' #' # matrix.files <- paste(system.file("extdata", package = "processedHiCdata"),
#' # "HiC-Pro/hESC_Rep1/hESC_Rep1_1000000_iced.matrix", sep = "/")
#' # bed.files <- paste(system.file("extdata", package = "processedHiCdata"),
#' # "HiC-Pro/hESC_Rep1/hESC_Rep1_1000000_abs.bed", sep = "/")
#' genomeBuild <- "hg19"
#' resolutions <- "1000000"
#' sampleName = "hESC1"
#' #HiCPro2DNAlandscapeR(matrix.files, bed.files, resolutions, sampleName = "hESC1", genomeBuild)
#' 

#' @export
setGeneric(name = "HiCPro2DNAlandscapeR", 
           def = function(matrix.files, bed.files, resolutions, sampleName, genomeBuild = NA, 
                          out.dir = "", drop.chrom = c("chrY", "chrM"), manual.chr = NA, manual.dist = NA,
                          BPPARAM = BiocParallel::bpparam())
               standardGeneric("HiCPro2DNAlandscapeR"))

#' @rdname HiCPro2DNAlandscapeR
setMethod("HiCPro2DNAlandscapeR",
         def = function(matrix.files, bed.files, resolutions, sampleName, genomeBuild = NA, 
                          out.dir = "", drop.chrom = c("chrY", "chrM"), manual.chr = NA, manual.dist = NA,
                          BPPARAM = BiocParallel::bpparam()) {
    
    
    dat <- import.HiCPro(matrix.files, bed.files, resolutions, sampleName, genomeBuild,
                         n = 40, drop.chrom, manual.chr, manual.dist, BPPARAM)
    # Output
    ss <- paste0(sampleName, "-HiC")
    warn <- "Do not edit this file; keep it in the same directory as the .rds for visualizing in DNAlandscapeR"
    outText <- c(warn, ss, paste(resolutions, collapse = ","))
    
    # Output .txt file
    fileConn<-file(paste0(out.dir, ss, ".resolutions.txt"))
    writeLines(outText, fileConn)
    close(fileConn)

    rdsFile<-file(paste0(out.dir, ss, ".rds"))
    saveRDS(dat, file = rdsFile)
})